// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Security.Data;

namespace Security.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20201204180744_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Security.Models.Docent", b =>
                {
                    b.Property<int>("DocentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DocentNaam")
                        .HasColumnType("TEXT");

                    b.HasKey("DocentId");

                    b.ToTable("Docenten");
                });

            modelBuilder.Entity("Security.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("StudentNaam")
                        .HasColumnType("TEXT");

                    b.HasKey("StudentId");

                    b.ToTable("Studenten");
                });

            modelBuilder.Entity("Security.Models.ToetsResultaat", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<int>("Cijfer")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DocentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("StudentId", "Datum");

                    b.HasIndex("DocentId");

                    b.ToTable("ToetsResultaten");
                });

            modelBuilder.Entity("Security.Models.ToetsResultaat", b =>
                {
                    b.HasOne("Security.Models.Docent", "Docent")
                        .WithMany("ToetsResultaten")
                        .HasForeignKey("DocentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Security.Models.Student", "Student")
                        .WithMany("ToetsResultaten")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Docent");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Security.Models.Docent", b =>
                {
                    b.Navigation("ToetsResultaten");
                });

            modelBuilder.Entity("Security.Models.Student", b =>
                {
                    b.Navigation("ToetsResultaten");
                });
#pragma warning restore 612, 618
        }
    }
}
