// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Studenten.Data;

namespace Studenten.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20201220185830_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10");

            modelBuilder.Entity("Studenten.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Leeftijd")
                        .HasColumnName("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naam")
                        .HasColumnName("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("StudentId");

                    b.ToTable("Student");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            Leeftijd = 21,
                            Naam = "Johan1"
                        },
                        new
                        {
                            StudentId = 2,
                            Leeftijd = 22,
                            Naam = "Johan2"
                        },
                        new
                        {
                            StudentId = 3,
                            Leeftijd = 23,
                            Naam = "Johan3"
                        },
                        new
                        {
                            StudentId = 4,
                            Leeftijd = 24,
                            Naam = "Johan4"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
