// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZoekFilterPagineer.Data;

namespace ZoekFilterPagineer.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ZoekFilterPagineer.Models.Cursus", b =>
                {
                    b.Property<int>("CursusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CursusNaam")
                        .HasColumnType("TEXT");

                    b.HasKey("CursusId");

                    b.ToTable("Cursussen");
                });

            modelBuilder.Entity("ZoekFilterPagineer.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Lengte")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StudentNaam")
                        .HasColumnType("TEXT");

                    b.HasKey("StudentId");

                    b.ToTable("Studenten");
                });

            modelBuilder.Entity("ZoekFilterPagineer.Models.StudentCursus", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CursusId")
                        .HasColumnType("INTEGER");

                    b.HasKey("StudentId", "CursusId");

                    b.HasIndex("CursusId");

                    b.ToTable("StudentCursussen");
                });

            modelBuilder.Entity("ZoekFilterPagineer.Models.StudentCursus", b =>
                {
                    b.HasOne("ZoekFilterPagineer.Models.Cursus", "Cursus")
                        .WithMany("StudentCursus")
                        .HasForeignKey("CursusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZoekFilterPagineer.Models.Student", "Student")
                        .WithMany("StudentCursus")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cursus");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ZoekFilterPagineer.Models.Cursus", b =>
                {
                    b.Navigation("StudentCursus");
                });

            modelBuilder.Entity("ZoekFilterPagineer.Models.Student", b =>
                {
                    b.Navigation("StudentCursus");
                });
#pragma warning restore 612, 618
        }
    }
}
