// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Validation.Data;

namespace Validation.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Validation.Models.Student", b =>
                {
                    b.Property<int>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Student_ID");

                    b.Property<string>("Achternaam")
                        .HasColumnType("TEXT")
                        .HasColumnName("Achternaam");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT")
                        .HasColumnName("Email");

                    b.Property<string>("Opleiding")
                        .HasColumnType("TEXT")
                        .HasColumnName("Opleiding");

                    b.Property<int>("Studiepunten")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Studiepunten");

                    b.Property<string>("Voornaam")
                        .HasColumnType("TEXT")
                        .HasColumnName("Voornaam");

                    b.Property<string>("Woonplaats")
                        .HasColumnType("TEXT")
                        .HasColumnName("Woonplaats");

                    b.HasKey("StudentID");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("Validation.Models.StudentVriend", b =>
                {
                    b.Property<int>("StudentID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Student_ID");

                    b.Property<int>("VriendID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Vriend_ID");

                    b.HasKey("StudentID", "VriendID");

                    b.HasIndex("VriendID");

                    b.ToTable("StudentVriend");
                });

            modelBuilder.Entity("Validation.Models.StudentVriend", b =>
                {
                    b.HasOne("Validation.Models.Student", "Student")
                        .WithMany("StudentVrienden")
                        .HasForeignKey("VriendID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Validation.Models.Student", b =>
                {
                    b.Navigation("StudentVrienden");
                });
#pragma warning restore 612, 618
        }
    }
}
